### ISSUE TITLE
Geo-location allows for out-of-radius access to the directory

### ISSUE THREAD

**Issue by musikame** [CampusMadridProjects/directory-frontend#31] opened 2018-09-19 08:37 UTC
I can access to the directory from Torre Picasso area/further than 100m around Campus

**Comment by ivoriginal** [comment] 2018-09-21 08:53
It's not a bug, it's a feature.

**Comment by CodingCarlos** [comment] 2018-09-27 15:43
This is caused for a missconfiguration in the backend, done by us, becouse of the random Malaga travels of the Campus IP :airplane: 

Closing this issue, to avoid confussion ;)

**Closed by CodingCarlos** 2018-09-27 15:43 UTC
Labels: bug
